features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: profiles/wunderhub/theme/wundersimple/favicon.ico
  mimetype: image/vnd.microsoft.icon
