name: WunderHub
mail: wunderhub@wunderkraut.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: 67bcdc00-cd22-49d6-a284-c068fe1dd333
